# Դասախոսություն 19
## Scikit-learn: Preprocessing
## Mariam Arzumanyan

Այսօր ուսումնասիրելու ենք sklearn.preprocessing-ի package-ը, որը մեզ հնարավորություն է տալիս ստանդարտացնելու մեր տվյալները։

Նախ, պետք է ներբեռնենք համապատասխան մոդուլները։


In [1]:
from sklearn import preprocessing
import numpy as np

sklearn.preprocessing-ից մեզ հետաքրքրում է StandardScaler class-ը։ 
https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html#sklearn.preprocessing.StandardScaler

In [2]:
from sklearn.preprocessing import StandardScaler

Ստանդարտացնում է feature-ները՝ հեռացնելով միջինը և չափավորելով ստանդարդ շեղումները։ 

In [3]:
x= [[0,0], [1,0], [1,1]]
scaler = StandardScaler()
scaler.fit(x)

StandardScaler()

In [4]:
print(scaler.mean_)

[0.66666667 0.33333333]


In [5]:
print(scaler.var_)

[0.22222222 0.22222222]


In [6]:
print(scaler.transform([[2,2]]))

[[2.82842712 3.53553391]]


In [7]:
z_1=(2-2/3)/np.sqrt(0.22222)
z_1

2.828441266987881

In [8]:
z_2=(2-1/3)/np.sqrt(0.22222)
z_2

3.535551583734851

In [9]:
print(scaler.transform(x))

[[-1.41421356 -0.70710678]
 [ 0.70710678 -0.70710678]
 [ 0.70710678  1.41421356]]


In [10]:
print(scaler.transform([[6,2], [1,1]]))

[[11.3137085   3.53553391]
 [ 0.70710678  1.41421356]]


In [11]:
print(scaler.transform(x))

[[-1.41421356 -0.70710678]
 [ 0.70710678 -0.70710678]
 [ 0.70710678  1.41421356]]


In [12]:
scaler.get_params(deep=True)

{'copy': True, 'with_mean': True, 'with_std': True}

In [13]:
scaler.get_params(deep=False)

{'copy': True, 'with_mean': True, 'with_std': True}

### Տնային Առաջադրանք 1
Հետևյալ տվյալների համար օգտագործեք StandardScaler()-ը ներքևում նշված հարցերին պատասխանելու համար։


In [19]:
x_1= [[1,1], [1,1], [1,0], [0,0], [0,0]]
x_2= [[2,5], [4.5, 8]]
x_3= [[1,1], [1,0], [0,0], [0,0], [0,1]]

Բոլոր 3 տվյալների համար, գրեք կոդ։
* Ներբեռնեք անհրաժեշտ մոդուլները։
* Fit x_1:
* Գտեք mean-ն ու var-ը։
* Transform արեք x_2-ն ու x_3-ը։

* Fit x_2:
* Գտեք mean-ն ու var-ը։
* Transform արեք x_1-ն ու x_3-ը։

* Fit x_3:
* Գտեք mean-ն ու var-ը։
* Transform արեք x_2-ն ու x_1-ը։

## MinMaxScaler 

class sklearn.preprocessing.MinMaxScaler(feature_range=(0, 1), *, copy=True, clip=False)

Այս ֆունկցիան ձևափոխում է տվյալները, ու բոլոր տվյալները լրացնում որոշակի տիրույթում։ 


\begin{equation}
X_{std} = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))
\end{equation}
\begin{equation}
X_{scaled} = X_{std} * (max - min) + min
\end{equation}

In [29]:
from sklearn.preprocessing import MinMaxScaler
x= [[0,-1], [2,0], [1,1]]
scaler = MinMaxScaler()
scaler.fit(x)

MinMaxScaler()

In [30]:
print(scaler.data_max_)
print(scaler.data_min_)

[2. 1.]
[ 0. -1.]


In [31]:
print(scaler.transform([[2,2]]))

[[1.  1.5]]


In [32]:
print(scaler.transform([[3,2]]))

[[1.5 1.5]]


In [36]:
z_1=[(3-0)/(2-0), (2-(-1))/(1-(-1))]
z_1

[1.5, 1.5]

### Տնային Առաջադրանք 2
Հետևյալ տվյալների համար օգտագործեք MinMaxScaler()-ը ներքևում նշված հարցերին պատասխանելու համար։


In [37]:
x_1= [[1,1], [1,1], [1,0], [0,0], [0,0]]
x_2= [[2,5], [4.5, 8]]
x_3= [[1,1], [1,0], [0,0], [0,0], [0,1]]

Բոլոր 3 տվյալների համար, գրեք կոդ։
* Ներբեռնեք անհրաժեշտ մոդուլները։
* Fit x_1:
* Գտեք mean-ն ու var-ը։
* Transform արեք x_2-ն ու x_3-ը։

* Fit x_2:
* Գտեք mean-ն ու var-ը։
* Transform արեք x_1-ն ու x_3-ը։

* Fit x_3:
* Գտեք mean-ն ու var-ը։
* Transform արեք x_2-ն ու x_1-ը։
* Համեմատեք այս վարժությունը StandardScaler()-ի պատասխանների հետ։

## OrdinalEncoder


class sklearn.preprocessing.OrdinalEncoder(*, categories='auto', dtype=<class 'numpy.float64'>, handle_unknown='error', unknown_value=None)

Այս ֆունկցիան փոխարինում է կատեգորիկ տվյալները թվային առանցքում, 0-ից մինչև կատեգորիաների քանակից մինուս 1։

In [57]:
from sklearn.preprocessing import OrdinalEncoder
enc = OrdinalEncoder()
X=[["Male"], ["Male"], ["Female"]]
enc.fit(X)

OrdinalEncoder()

In [58]:
enc.categories_

[array(['Female', 'Male'], dtype=object)]

In [59]:
print(enc.transform([["Female"], ["Male"]]))

[[0.]
 [1.]]


In [60]:
x=[[-1, "zebra"], [-2, "lion"], [0, "tiger"], [-1, "lion"]]
enc.fit(x)
enc.categories_

[array([-2, -1, 0], dtype=object),
 array(['lion', 'tiger', 'zebra'], dtype=object)]

In [61]:
enc.transform(x)

array([[1., 2.],
       [0., 0.],
       [2., 1.],
       [1., 0.]])

Թվերի դեպքում ալգորիթմը սկսում է ամենափոքր թվից, տառերի դեպքում ալգորիթմը սկսում է աշխատել այբենական կարգով։

## Տնային Առաջադրանք 3

Հետևյալ տվյալների համար, պատասխանեք ներքևում տրված հարցերին։


In [63]:
x_1=[[0, "zebra"], [-1, "lion"], [0, "tiger"], [0, "lion"], [-1, "zebra"]]
x_2=[["bird", "boy", -10],["fish", "boy", 4], ["mammal", "girl", 2], ["fish", "girl", 1]]
x_3=[["bird", "girl", 4],["fish", "girl", 2], ["mammal", "boy", 2], ["fish", "girl", 1]]

Բոլոր 3 տվյալների համար, գրեք կոդ։
* Ներբեռնեք անհրաժեշտ մոդուլները։
* Fit x_1:
* Գտեք բոլոր կատեգորիաները։
* Transform արեք x_1-ն։
* inverse transform արեք x_1-ն։


* Fit x_2:
* Գտեք բոլոր կատեգորիաները։
* Transform արեք x_2-ն։
* inverse transform արեք x_2-ն։

* Fit x_3:
* Գտեք բոլոր կատեգորիաները։
* Transform արեք x_3-ն։
* inverse transform արեք x_3-ն։
* Համեմատեք այս վարժությունը  պատասխանները x_1-ի, x_2-ի ու x_3-ի համար։

## OneHotEncoder

class sklearn.preprocessing.OneHotEncoder(*, categories='auto', drop=None, sparse=True, dtype=<class 'numpy.float64'>, handle_unknown='error')

In [66]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(handle_unknown='ignore')
X=[["Male"], ["Male"], ["Female"]]
enc.fit(X)
enc.categories_

[array(['Female', 'Male'], dtype=object)]

In [69]:
enc.transform(X).toarray()

array([[0., 1.],
       [0., 1.],
       [1., 0.]])

In [79]:
X=[["Male", 1], ["Male", 0], ["Female",2]]
enc.fit(X)
enc.categories_

[array(['Female', 'Male'], dtype=object), array([0, 1, 2], dtype=object)]

In [86]:
s=enc.transform(X)
s.shape
s.toarray()

array([[0., 1., 0., 1., 0.],
       [0., 1., 1., 0., 0.],
       [1., 0., 0., 0., 1.]])

## Binarizer

class sklearn.preprocessing.Binarizer(*, threshold=0.0, copy=True)

Կախված շեմից, այս ֆունկցիան մեզ վերադարձնում է կամ 0 կամ 1։

In [101]:
from sklearn.preprocessing import Binarizer
scaler=Binarizer()
x=[[1,1], [2,-1], [0,1], [0,0], [-2, 1]]
scaler.fit(x)

Binarizer()

In [102]:
scaler.transform(x)

array([[1, 1],
       [1, 0],
       [0, 1],
       [0, 0],
       [0, 1]])

In [104]:
scaler=Binarizer(threshold=1.1)
scaler.fit(x)

Binarizer(threshold=1.1)

In [105]:
scaler.transform(x)

array([[0, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

## KBinsDiscretizer

class sklearn.preprocessing.KBinsDiscretizer(n_bins=5, *, encode='onehot', strategy='quantile', dtype=None)[source]

Այս ֆունկցիան բաժանում է անընդհատ տվյալների բազմությունը վերջավոր խմբերի։ 

In [92]:
from sklearn.preprocessing import KBinsDiscretizer
x= [[0,-1], [2,0], [1,1]]
scaler=KBinsDiscretizer(n_bins=2, encode='ordinal', strategy='uniform')
scaler.fit(x)

KBinsDiscretizer(encode='ordinal', n_bins=2, strategy='uniform')

In [93]:
print(scaler.transform([[2,2], [1,-1]]))

[[1. 1.]
 [1. 0.]]


In [94]:
print(scaler.transform([[0,6], [1,-3]]))

[[0. 1.]
 [1. 0.]]


In [52]:
x=scaler.transform(x)
x

array([[0., 1.],
       [2., 2.],
       [1., 2.]])

In [96]:
age=[[1],[1.5], [1], [2],[2],[2],[3],[3],[3],[4],[5],[6],[7],[8],[9], [10]]
scaler=KBinsDiscretizer(n_bins=3, encode='ordinal', strategy='uniform')
scaler.fit(age) 

KBinsDiscretizer(encode='ordinal', n_bins=3, strategy='uniform')

In [97]:
scaler.transform(age)

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [2.],
       [2.],
       [2.],
       [2.]])